service: algo-price-oracle

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  environment:
    ALGO_CHAIN: test
    ORACLE_APP_ID: ${ssm:/darksky-api-key~true}

functions:
  main:
    handler: handler.main
    events:
      - schedule: rate(5 minutes)