service: algo-price-oracle

frameworkVersion: '2'

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    ALGO_CHAIN:
      production: "main"
      development: "test"
    ORACLE_APP_ID:
      production: "main"
      development: "57064474"
    ADMIN_WALLET_ADDRESS:
      production: ""
      development: "test"
    ADMIN_PRIVATE_KEY:
      production: ""
      development: ${ssm:/path/to/service/id}
    ALGOD_ADDRESS:
      production: "https://algoexplorerapi.io"
      development: "https://testnet.algoexplorerapi.io"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: development
  region: eu-west-1
  environment:
    ALGO_CHAIN: ${self:custom.environment.ALGO_CHAIN.${self:custom.stage}}
    ORACLE_APP_ID: ${self:custom.environment.ORACLE_APP_ID.${self:custom.stage}}
    ADMIN_WALLET_ADDRESS: ${self:custom.environment.ADMIN_WALLET_ADDRESS.${self:custom.stage}}
    ADMIN_PRIVATE_KEY: ${self:custom.environment.ADMIN_PRIVATE_KEY.${self:custom.stage}}
    ALGOD_ADDRESS: ${self:custom.environment.ALGOD_ADDRESS.${self:custom.stage}}

functions:
  main:
    handler: handler.main
    events:
      - schedule: rate(5 minutes)