service: algo-price-oracle

frameworkVersion: '2'

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    ALGO_CHAIN:
      production: "main"
      development: "test"
    ORACLE_APP_ID:
      production: "main"
      development: "57082823"
    ALGOD_ADDRESS:
      production: "https://algoexplorerapi.io"
      development: "https://testnet.algoexplorerapi.io"


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: development
  region: eu-west-1
  environment:
    ALGO_CHAIN: ${self:custom.environment.ALGO_CHAIN.${self:custom.stage}}
    ORACLE_APP_ID: ${self:custom.environment.ORACLE_APP_ID.${self:custom.stage}}
    ALGOD_ADDRESS: ${self:custom.environment.ALGOD_ADDRESS.${self:custom.stage}}
    SECRET_NAME: ${opt:secret_name}
    AWS_REGION: ${opt:aws_region}
functions:
  main:
    handler: handler.main
    events:
      - schedule: rate(5 minutes)