name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: AWS SAM Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - uses: aws-actions/setup-sam@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SHARED_SERVICES_DEVELOPMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHARED_SERVICES_DEVELOPMENT }}
          aws-region: eu-west-1

      - run: sam build --use-container

      - run: sam deploy --config-env development --no-confirm-changeset

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ always() }}
        env:
          SLACK_TITLE: "Algorand Price Oracle Deployment"
          SLACK_USERNAME: "Github"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_FEED_DEPLOYMENTS }}